### ISSUE TITLE
Usunięcie 

### ISSUE THREAD

**Issue by Superbizons** [Ewaldd/EwaldBot#6]
Proponuję usunąć folder. idea, ponieważ zawiera on twoje ustawienia z intellij i jest zbędny =).

**Comment by Reedzev** [comment]
Nie tylko .idea.

**Comment by Superbizons** [comment]
Ale między innymi.

**Comment by Ewaldd** [comment]
Zrobione. Podziękowania dla @kacperduras za pomoc :>

**Comment by Ewaldd** [comment]
#9
